// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingCenter.Data;

#nullable disable

namespace TrainingCenter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930165454_newddsbs")]
    partial class newddsbs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingCenter.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseCode")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("TrainingCenter.Models.Lectures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseCode")
                        .HasColumnType("int");

                    b.Property<int?>("CourseIDId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseIDId");

                    b.ToTable("Lecturess");
                });

            modelBuilder.Entity("TrainingCenter.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseCode")
                        .HasColumnType("int");

                    b.Property<int?>("CourseIDId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseIDId");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("TrainingCenter.Models.TrainingCenterCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("trainingCenterCourses");
                });

            modelBuilder.Entity("TrainingCenter.Models.Lectures", b =>
                {
                    b.HasOne("TrainingCenter.Models.Course", "CourseID")
                        .WithMany()
                        .HasForeignKey("CourseIDId");

                    b.Navigation("CourseID");
                });

            modelBuilder.Entity("TrainingCenter.Models.Subject", b =>
                {
                    b.HasOne("TrainingCenter.Models.Course", "CourseID")
                        .WithMany()
                        .HasForeignKey("CourseIDId");

                    b.Navigation("CourseID");
                });

            modelBuilder.Entity("TrainingCenter.Models.TrainingCenterCourse", b =>
                {
                    b.HasOne("TrainingCenter.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
