// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingCenter.Data;

#nullable disable

namespace TrainingCenter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250927113415_newdatrs")]
    partial class newdatrs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingCenter.Models.CourseCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeAdvancedCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeFoundationalCourse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("courseCodes");
                });

            modelBuilder.Entity("TrainingCenter.Models.Cuorse", b =>
                {
                    b.Property<int>("CuorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuorseId"));

                    b.Property<int?>("CuoresHouers")
                        .HasColumnType("int");

                    b.Property<string>("CuorseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuorseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LectuerId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CuorseId");

                    b.ToTable("Cuorse");
                });

            modelBuilder.Entity("TrainingCenter.Models.TrainingCenterCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CuorsesCuorseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuorsesCuorseId");

                    b.ToTable("trainingCenterCourses");
                });

            modelBuilder.Entity("TrainingCenter.Models.TrainingCenterCourse", b =>
                {
                    b.HasOne("TrainingCenter.Models.Cuorse", "Cuorses")
                        .WithMany()
                        .HasForeignKey("CuorsesCuorseId");

                    b.Navigation("Cuorses");
                });
#pragma warning restore 612, 618
        }
    }
}
